In [1]:
import numpy as np 


In [2]:
x= np.array([1,2,3,4])
print(x)

[1 2 3 4]


In [3]:
y=[1,2,3,4]
print(y)

[1, 2, 3, 4]


In [8]:
%timeit [j**4 for j in range(1,9)]

288 ns ± 2.99 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [7]:
%timeit  np.arange(1,9)**4

834 ns ± 2.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


# Array

 ### Types
        - 1-D array = [1 2 3 4]
        - 2-D array = [[1 2 3 4]]
        - 3D array = [[[1 2 3 4]]]

In [14]:
x= np.array([1,2,3,4])
print(x)

print(x.ndim)

[1 2 3 4]
1


In [12]:
l =[]


for i in range(1,5):
    int_1 = int(input("ENter the value"))
    l.append(int_1)
print(np.array(l))

ENter the value 1
ENter the value 2
ENter the value 3
ENter the value 4


[1 2 3 4]


In [15]:
l=np.array([[1,2,3,4],[5,6,7,8]])

In [18]:
print(l)
print(l.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [22]:
p=np.array([[[1,2,3,4],[5,6,7,8]]])
print(l)
print(p.ndim)

[[[1 2 3 4]
  [5 6 7 8]]]
3


# Zeros

In [28]:
a = np.zeros(4)
a

array([0., 0., 0., 0.])

In [29]:
b = np.zeros((3,2))
b

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

# ones

In [31]:
c =np.ones(3)
c

array([1., 1., 1.])

In [33]:
d = np.ones((4,5))
d

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# Empty

In [35]:
e =np.empty(4)
e

array([0., 0., 0., 0.])

# range of elements

In [36]:
f = np.arange(4)
f

array([0, 1, 2, 3])

# diagonal element same

In [37]:
g = np.eye(3)
g

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
h = np.eye(5,5)
h

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# In a specific interval with gap

In [41]:
linspace= np.linspace(0,10,num=5)
linspace

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# Fuctions in array

In [42]:
# Random = rand()

ok = np.random.rand(10)
ok

array([0.50409153, 0.87854633, 0.11124168, 0.19221759, 0.95675956,
       0.8199549 , 0.08095305, 0.6829608 , 0.8928386 , 0.28998718])

In [43]:
o = np.random.rand(3,4)
o

array([[0.94453331, 0.07621094, 0.6935316 , 0.62315219],
       [0.36131843, 0.12018972, 0.69443595, 0.08834265],
       [0.27571542, 0.1359148 , 0.55344926, 0.49684942]])

In [45]:
# randn()

okk = np.random.randn(10)
okk

array([ 0.416648  ,  1.4124844 ,  0.02279543,  0.10477274,  0.24274538,
       -0.71726002, -0.40882291, -0.63416287,  0.02811099, -0.83417002])

In [47]:
lp = np.random.randn(3,4)
lp

array([[-0.73264616,  0.43488472, -0.07450433,  0.18116925],
       [ 0.85436566,  1.98328789, -0.66202956, -1.14956203],
       [ 1.04792839,  1.67194605, -0.34742077, -0.25513895]])

In [48]:
#ranf()

k = np.random.ranf(10)
k

array([0.28967   , 0.58729437, 0.86069579, 0.97001937, 0.77448388,
       0.92129103, 0.10260293, 0.29940809, 0.07456841, 0.52114285])

In [51]:
kk = np.random.ranf(3)
kk

array([0.57477063, 0.19872311, 0.11300851])

In [52]:
# randint()

ni = np.random.randint(3,10,20)
ni


array([5, 9, 6, 5, 7, 7, 6, 3, 8, 3, 7, 6, 3, 4, 7, 5, 8, 5, 4, 5])